<a href="https://colab.research.google.com/github/kb4721/Project1/blob/main/WebScraping_pesDb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

pos = 12
URL = f'https://pesdb.net/pes2022/?mode=max_level&all=1&pos={pos}&offensive_awareness=41-99&ball_control=41-99&dribbling=41-99&tight_possession=41-99&low_pass=41-99&lofted_pass=41-99&finishing=41-99&heading=41-99&set_piece_taking=41-99&curl=41-99&speed=41-99&acceleration=41-99&kicking_power=41-99&jumping=41-99&physical_contact=41-99&balance=41-99&stamina=41-99&defensive_awareness=41-99&tackling=41-99&aggression=41-99&defensive_engagement=41-99&gk_awareness=40-98&gk_catching=40-98&gk_parrying=40-98&gk_reflexes=40-98&gk_reach=40-98&overall_rating=80-100&sort=id&order=a'

result = requests.get(URL)

print(result)
content = result.text

soup = BeautifulSoup(content, 'lxml')


table = soup.find('table', class_ = 'players')

headers = table.find_all('th')

titles = []
for i in headers:
    title = i.text
    titles.append(title)

titles

<Response [200]>

['ID',
 'Position',
 'Player Name',
 'Team Name',
 'Nationality',
 'Height',
 'Weight',
 'Age',
 'Offensive Awareness',
 'Ball Control',
 'Dribbling',
 'Tight Possession',
 'Low Pass',
 'Lofted Pass',
 'Finishing',
 'Heading',
 'Set Piece Taking',
 'Curl',
 'Speed',
 'Acceleration',
 'Kicking Power',
 'Jumping',
 'Physical Contact',
 'Balance',
 'Stamina',
 'Defensive Awareness',
 'Tackling',
 'Aggression',
 'Defensive Engagement',
 'GK Awareness',
 'GK Catching',
 'GK Parrying',
 'GK Reflexes',
 'GK Reach',
 'Overall Rating',
 'Price']

In [ ]:
df = pd.DataFrame(columns=titles)
df

Empty DataFrame
Columns: [ID, Position, Player Name, Team Name, Nationality, Height, Weight, Age, Offensive Awareness, Ball Control, Dribbling, Tight Possession, Low Pass, Lofted Pass, Finishing, Heading, Set Piece Taking, Curl, Speed, Acceleration, Kicking Power, Jumping, Physical Contact, Balance, Stamina, Defensive Awareness, Tackling, Aggression, Defensive Engagement, GK Awareness, GK Catching, GK Parrying, GK Reflexes, GK Reach, Overall Rating, Price]
Index: []

[0 rows x 36 columns]

In [ ]:
values = table.find_all('tr')
values[2].text

'7889CFC. KeșerüFree AgentsRomania17871367768696559567770677175797671687874475159484040404040814.100'

In [ ]:
players = []
for i in range(1, len(values)):
  player = values[i]
  pl = []
  for j in player:
        pl.append(j.text)
  players.append(pl)

In [ ]:
for x in players:
  df.loc[len(df)] = x

In [ ]:
df

,ID,Position,Player Name,Team Name,Nationality,Height,Weight,Age,Offensive Awareness,Ball Control,...,Tackling,Aggression,Defensive Engagement,GK Awareness,GK Catching,GK Parrying,GK Reflexes,GK Reach,Overall Rating,Price
0,3707,CF,M. Boselli,Club Estudiantes LP,Argentina,180,80,37,85,78,...,41,47,47,40,40,40,40,40,86,7.500
1,7889,CF,C. Keșerü,Free Agents,Romania,178,71,36,77,68,...,51,59,48,40,40,40,40,40,81,4.100
2,8944,CF,K. Benzema,Free Agents,France,185,81,35,90,86,...,49,63,60,40,40,40,40,40,96,740.000
3,9182,CF,J. Ménez,Reggina 1914,France,183,79,35,80,78,...,46,58,45,40,40,40,40,40,84,4.700
4,15038,CF,Hulk,Free Agents,Brazil,180,85,36,84,77,...,49,69,48,40,40,40,40,40,90,0
5,15452,CF,S. Nagasawa,Oita Trinita,Japan,192,82,34,77,72,...,50,58,48,40,40,40,40,40,80,3.400
6,16409,CF,K. Sugimoto,Yokohama F. Marinos,Japan,187,79,30,75,72,...,54,52,53,40,40,40,40,40,80,0
7,16513,CF,Douglas,Kashiwa Reysol,Brazil,184,80,35,78,79,...,42,43,48,40,40,40,40,40,80,4.900
8,30323,CF,K. Gameiro,RC Strasbourg Alsace,France,172,69,35,81,74,...,46,58,61,40,40,40,40,40,84,14.000
9,31044,CF,R. Falcao,Vallecas BR,Colombia,177,72,36,86,76,...,42,56,53,40,40,40,40,40,85,32.000
10,32199,CF,F. Quagliarella,Liguria B,Italy,180,79,39,87,77,...,42,49,43,40,40,40,40,40,85,15.000
11,32436,CF,L. López,CA Sarmiento,Argentina,174,74,39,81,77,...,43,59,52,40,40,40,40,40,83,10.000
12,33491,CF,G. Torres,Free Agents,Panama,179,78,34,82,72,...,46,50,46,40,40,40,40,40,82,4.700
13,33633,CF,G. Higuaín,Free Agents,Argentina,186,89,35,85,74,...,41,48,48,40,40,40,40,40,87,0
14,33784,CF,Soldado,Levante RA,Spain,180,74,37,82,76,...,49,67,50,40,40,40,40,40,84,10.000
15,34005,CF,Álvaro Negredo,Cádiz AA,Spain,186,86,37,84,77,...,46,65,49,40,40,40,40,40,87,14.000
16,34626,CF,S. Long,Free Agents,Ireland,178,81,35,79,69,...,46,70,52,40,40,40,40,40,84,5.900
17,34813,CF,M. Arnautović,Bologna RB,Austria,189,95,33,81,76,...,43,56,69,40,40,40,40,40,86,22.000
18,34862,CF,B. Yılmaz,Free Agents,Türkiye,188,80,37,84,69,...,52,71,64,40,40,40,40,40,85,32.000
19,34881,CF,L. Suárez,Grêmio FBPA,Uruguay,182,83,35,91,77,...,43,76,57,40,40,40,40,40,89,82.000
20,35266,CF,Alexandre Pato,Free Agents,Brazil,180,78,33,80,76,...,41,50,48,40,40,40,40,40,85,0
21,35477,CF,E. Cavani,CA Boca Juniors,Uruguay,184,71,35,90,74,...,48,72,79,40,40,40,40,40,90,76.000
22,35508,CF,K. Lafferty,Free Agents,Northern Ireland,193,71,35,77,68,...,48,65,48,40,40,40,40,40,80,0
23,36556,CF,Chicharito,Los Angeles WBY,Mexico,175,73,34,86,72,...,46,58,59,40,40,40,40,40,86,10.000
24,36718,CF,A. Sánchez,Olympique de Marseille,Chile,168,62,34,86,81,...,49,57,62,40,40,40,40,40,89,34.000
25,36821,CF,H. Barcos,Alianza Lima,Argentina,187,92,38,80,75,...,46,65,47,40,40,40,40,40,84,5.900
26,36895,CF,B. Sharp,Free Agents,England,178,70,36,82,72,...,44,55,68,40,40,40,40,40,83,0
27,37028,CF,A. Ayew,Free Agents,Ghana,176,72,33,82,71,...,52,59,61,40,40,40,40,40,85,8.000
28,37148,CF,J. Larrivey,Maipú A,Argentina,186,81,38,76,68,...,45,52,46,40,40,40,40,40,80,7.500
29,37304,CF,C. Stuani,Girona R,Uruguay,186,77,36,85,73,...,50,67,58,40,40,40,40,40,87,14.000
30,37638,CF,E. Džeko,Fenerbahçe SK,Bosnia and Herzegovina,193,80,36,91,79,...,49,60,55,40,40,40,40,40,90,82.000
31,37899,CF,M. Moreno,Free Agents,Bolivia,187,89,35,80,67,...,50,62,44,40,40,40,40,40,83,4.700

In [ ]:
headers = table.find_all('th')

titles = []
for i in headers:
    title = i.text
    titles.append(title)

titles
df2 = pd.DataFrame(columns=titles)

In [ ]:
page =2
while True:
  url = f'https://pesdb.net/pes2022/?mode=max_level&all=1&pos={pos}&offensive_awareness=41-99&ball_control=41-99&dribbling=41-99&tight_possession=41-99&low_pass=41-99&lofted_pass=41-99&finishing=41-99&heading=41-99&set_piece_taking=41-99&curl=41-99&speed=41-99&acceleration=41-99&kicking_power=41-99&jumping=41-99&physical_contact=41-99&balance=41-99&stamina=41-99&defensive_awareness=41-99&tackling=41-99&aggression=41-99&defensive_engagement=41-99&gk_awareness=40-98&gk_catching=40-98&gk_parrying=40-98&gk_reflexes=40-98&gk_reach=40-98&overall_rating=80-100&sort=id&order=a&page={page}'
  result = requests.get(url)
  content = result.text

  soup = BeautifulSoup(content, 'lxml')


  table = soup.find('table', class_ = 'players')

  values = table.find_all('tr')
  players = []
  for i in range(1, len(values)):
    player = values[i]
    pl = []
    for j in player:
        pl.append(j.text)
    players.append(pl)

  for x in players:
      df.loc[len(df)] = x

  page += 1

  if page == 30:
    break

In [ ]:
df

,ID,Position,Player Name,Team Name,Nationality,Height,Weight,Age,Offensive Awareness,Ball Control,...,Tackling,Aggression,Defensive Engagement,GK Awareness,GK Catching,GK Parrying,GK Reflexes,GK Reach,Overall Rating,Price
0,3707,CF,M. Boselli,Club Estudiantes LP,Argentina,180,80,37,85,78,...,41,47,47,40,40,40,40,40,86,7.500
1,7889,CF,C. Keșerü,Free Agents,Romania,178,71,36,77,68,...,51,59,48,40,40,40,40,40,81,4.100
2,8944,CF,K. Benzema,Free Agents,France,185,81,35,90,86,...,49,63,60,40,40,40,40,40,96,740.000
3,9182,CF,J. Ménez,Reggina 1914,France,183,79,35,80,78,...,46,58,45,40,40,40,40,40,84,4.700
4,15038,CF,Hulk,Free Agents,Brazil,180,85,36,84,77,...,49,69,48,40,40,40,40,40,90,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
923,53877412044292,CF,Y. Suzuki,Kashima Antlers,Japan,182,75,26,79,74,...,61,59,74,40,40,40,40,40,88,0
924,53877412045677,CF,Thiago Santana,Shimizu S-Pulse,Brazil,184,80,29,81,78,...,60,70,61,40,40,40,40,40,88,0
925,53877412062525,CF,Y. Yamagishi,Avispa Fukuoka,Japan,183,80,29,73,77,...,63,69,64,40,40,40,40,40,85,0
926,53877412063593,CF,T. Miyashiro,Kawasaki Frontale,Japan,178,73,22,72,77,...,56,58,60,40,40,40,40,40,84,0
927,53877680480548,CF,B. Dost,FC Utrecht,Netherlands,196,86,33,85,75,...,53,76,73,40,40,40,40,40,90,0

In [ ]:
df.to_csv('CF.csv')